spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: pg
    password: pg
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
      
build:
  version: "2.0"

loans:
  message: "Eazybank local APIs"
  contactDetails:
    name: "Jesse - QA Lead"
    email: "j@eazybank.com"
  onCallSupport:
    - (111)111-1111
    - (222)222-2222
